# gem. Versions and up are supported.
#   gem install sqlite3
#
#   Ensure the MySQL gem is defined in your Gemfile
#   gem "mysql"
#

default: &default
  adapter: mysql2
  encoding:  utf8mb4
  collation: utf8mb4_spanish2_ci  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: polleria_development

test:
  <<: *default
  database: polleria_test

production:
  <<: *default
  database: polleria_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
